#!/usr/bin/env python3
"""
run_unit_assessment_batch.py — generic unit assessment batch runner.

Plans and executes unit_assessment extractions for a list of page windows.
Windows are generated by plan_extraction_ranges.plan() (structural section
detection) or can be restricted by --start-page/--end-page.

Each window is run as a separate extract_case() call (focus=unit_assessment,
batch_by_section=False).  Transient empty responses are retried once by
default.  Failures in one window do not abort the rest.

Never promotes to data/cases/.  Generated drafts/reports remain in
data/drafts/ and are gitignored.

Usage (from apps/api/):
    # Dry-run — see commands without calling Claude:
    .venv/bin/python scripts/cases/run_unit_assessment_batch.py \\
        --case-id <case_id> \\
        --start-page 60 --end-page 250 \\
        --max-units 8 \\
        --dry-run

    # Real run:
    .venv/bin/python scripts/cases/run_unit_assessment_batch.py \\
        --case-id <case_id> \\
        --start-page 60 --end-page 250 \\
        --max-units 8 \\
        --max-cost 2.00
"""

from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# Path setup — must precede all local imports
# ---------------------------------------------------------------------------

_SCRIPTS_DIR = Path(__file__).resolve().parent
_API_DIR = _SCRIPTS_DIR.parent.parent
_REPO_ROOT = _API_DIR.parents[1]

for _p in (str(_API_DIR), str(_SCRIPTS_DIR)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import yaml

from app.shared.utils.pdf_extractor import DEFAULT_CACHE_DIR
from extract_case_from_source import _resolve_canonical_yaml, extract_case
from plan_extraction_ranges import (
    ProbeWindow,
    _load_source_cache,
    _resolve_cache_path,
    plan,
)

_CASES_DIR = _REPO_ROOT / "data" / "cases"
_DRAFTS_DIR = _REPO_ROOT / "data" / "drafts"

# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class WindowResult:
    label: str                         # context_suffix from ProbeWindow
    page_range: tuple[int, int]
    output_suffix: str                 # full suffix used for draft file name
    draft_path: Path
    status: str                        # pass | empty | failed | skipped | skipped_existing | dry_run
    units_extracted: int = 0
    findings: int = 0
    siec: int = 0
    no_siec: int = 0
    discussed: int = 0
    other_conclusion: int = 0
    source_passages: int = 0
    retries: int = 0
    boundary_warning: bool = False     # True when >1 distinct unit label in one draft
    error: Optional[str] = None
    command: str = ""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_suffix(context_suffix: str) -> str:
    """Build --output-suffix from a ProbeWindow's context_suffix."""
    return f"unit_{context_suffix}"


def _make_command(
    case_id: str,
    window: ProbeWindow,
    suffix: str,
    max_cost: float,
) -> str:
    """Return the ingest_case.py CLI command equivalent for a window.

    Intentionally omits --batch-by-section: unit_assessment always uses
    single-batch mode (the guard in extract_case_from_source enforces this,
    but the command string should also be correct).
    """
    return (
        f"apps/api/.venv/bin/python apps/api/scripts/cases/ingest_case.py"
        f" --case-id {case_id}"
        f" --focus unit_assessment"
        f" --page-range {window.start_page}:{window.end_page}"
        f" --output-suffix {suffix}"
        f" --max-cost {max_cost:.2f}"
    )


def _read_draft_unit_stats(draft_path: Path) -> dict:
    """Parse a draft YAML; return unit/finding counts and unit labels."""
    empty: dict = {
        "units": 0, "findings": 0, "siec": 0,
        "no_siec": 0, "discussed": 0, "other_conclusion": 0,
        "source_passages": 0, "unit_labels": [],
    }
    if not draft_path.exists():
        return empty
    try:
        d = yaml.safe_load(draft_path.read_text(encoding="utf-8")) or {}
    except Exception:
        return empty

    uas = d.get("unit_assessments") or []
    labels = [u.get("unit_label", "") for u in uas]
    findings_total = siec = no_siec = discussed = other = 0
    for u in uas:
        for f in (u.get("findings") or []):
            findings_total += 1
            c = (f.get("conclusion") or "").strip()
            if c == "siec":
                siec += 1
            elif c == "no_siec":
                no_siec += 1
            elif c == "discussed":
                discussed += 1
            else:
                other += 1
    return {
        "units": len(uas),
        "findings": findings_total,
        "siec": siec,
        "no_siec": no_siec,
        "discussed": discussed,
        "other_conclusion": other,
        "source_passages": len(d.get("source_passages") or []),
        "unit_labels": labels,
    }


def _run_window(
    window: ProbeWindow,
    case_id: str,
    yaml_path: Path,
    cache_dir: Path,
    draft_dir: Path,
    anthropic_client,
    max_cost: float,
    retry_empty: bool,
    dry_run: bool,
    skip_existing: bool = False,
) -> WindowResult:
    """Run extraction for one ProbeWindow; return a WindowResult.

    Never raises — errors are captured into WindowResult.status / .error.
    """
    suffix = _make_suffix(window.context_suffix)
    stem = f"{case_id}.unit_assessment.{suffix}"
    draft_path = draft_dir / f"{stem}.draft.yaml"
    command = _make_command(case_id, window, suffix, max_cost)

    if dry_run:
        if skip_existing and draft_path.exists():
            stats = _read_draft_unit_stats(draft_path)
            return WindowResult(
                label=window.context_suffix,
                page_range=(window.start_page, window.end_page),
                output_suffix=suffix,
                draft_path=draft_path,
                status="skipped_existing",
                units_extracted=stats["units"],
                findings=stats["findings"],
                siec=stats["siec"],
                no_siec=stats["no_siec"],
                discussed=stats["discussed"],
                other_conclusion=stats["other_conclusion"],
                source_passages=stats["source_passages"],
                command=command,
            )
        return WindowResult(
            label=window.context_suffix,
            page_range=(window.start_page, window.end_page),
            output_suffix=suffix,
            draft_path=draft_path,
            status="dry_run",
            command=command,
        )

    if skip_existing and draft_path.exists():
        stats = _read_draft_unit_stats(draft_path)
        return WindowResult(
            label=window.context_suffix,
            page_range=(window.start_page, window.end_page),
            output_suffix=suffix,
            draft_path=draft_path,
            status="skipped_existing",
            units_extracted=stats["units"],
            findings=stats["findings"],
            siec=stats["siec"],
            no_siec=stats["no_siec"],
            discussed=stats["discussed"],
            other_conclusion=stats["other_conclusion"],
            source_passages=stats["source_passages"],
            command=command,
        )

    def _attempt() -> tuple[str, Optional[str]]:
        try:
            rpt = extract_case(
                yaml_path,
                cache_dir=cache_dir,
                output_path=draft_path,
                use_claude=True,
                anthropic_client=anthropic_client,
                focus="unit_assessment",
                max_cost=max_cost,
                batch_by_section=False,
                page_range=(window.start_page, window.end_page),
            )
        except Exception as exc:
            return "failed", str(exc)
        if rpt.error:
            return "failed", rpt.error
        stats = _read_draft_unit_stats(draft_path)
        if stats["units"] == 0:
            return "empty", None
        return "pass", None

    retries = 0
    status, error = _attempt()
    if status == "empty" and retry_empty:
        retries = 1
        status, error = _attempt()

    stats = _read_draft_unit_stats(draft_path)
    unique_labels = [lb for lb in set(stats["unit_labels"]) if lb]
    boundary_warning = len(unique_labels) > 1

    return WindowResult(
        label=window.context_suffix,
        page_range=(window.start_page, window.end_page),
        output_suffix=suffix,
        draft_path=draft_path,
        status=status,
        units_extracted=stats["units"],
        findings=stats["findings"],
        siec=stats["siec"],
        no_siec=stats["no_siec"],
        discussed=stats["discussed"],
        other_conclusion=stats["other_conclusion"],
        source_passages=stats["source_passages"],
        retries=retries,
        boundary_warning=boundary_warning,
        error=error,
        command=command,
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def run_batch(
    case_id: str,
    start_page: Optional[int] = None,
    end_page: Optional[int] = None,
    max_units: Optional[int] = None,
    window_size: int = 20,
    max_cost: float = 2.00,
    retry_empty: bool = True,
    dry_run: bool = False,
    skip_existing: bool = False,
    anthropic_client=None,
    cache_dir: Optional[Path] = None,
) -> list[WindowResult]:
    """Plan and run unit_assessment extractions for a case.

    Returns one WindowResult per planned window (capped at max_units).
    Continues on per-window failures — never promotes to data/cases/.
    """
    if cache_dir is None:
        cache_dir = DEFAULT_CACHE_DIR

    yaml_path = _resolve_canonical_yaml(case_id, _CASES_DIR)
    if yaml_path is None:
        raise ValueError(f"No canonical YAML found for '{case_id}' under {_CASES_DIR}")

    with open(yaml_path) as fh:
        record = yaml.safe_load(fh)
    jurisdiction = (record.get("jurisdiction") or "unknown").lower()
    draft_dir = _DRAFTS_DIR / jurisdiction
    draft_dir.mkdir(parents=True, exist_ok=True)

    cache_path = _resolve_cache_path(case_id)
    if cache_path is None:
        raise ValueError(
            f"No source cache found for '{case_id}'. "
            "Run ingest_case.py first to populate the source cache."
        )
    source_cache = _load_source_cache(cache_path)

    page_range: Optional[tuple[int, int]] = None
    if start_page is not None or end_page is not None:
        lo = start_page if start_page is not None else 1
        hi = end_page if end_page is not None else source_cache.get("page_count", 9999)
        page_range = (lo, hi)

    windows = plan(source_cache, focus="unit_assessment", page_range=page_range, window_size=window_size)
    if max_units is not None:
        windows = windows[:max_units]

    results: list[WindowResult] = []
    for window in windows:
        result = _run_window(
            window=window,
            case_id=case_id,
            yaml_path=yaml_path,
            cache_dir=cache_dir,
            draft_dir=draft_dir,
            anthropic_client=anthropic_client,
            max_cost=max_cost,
            retry_empty=retry_empty,
            dry_run=dry_run,
            skip_existing=skip_existing,
        )
        results.append(result)

    return results


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------


def format_batch_report(results: list[WindowResult], case_id: str) -> str:
    """Format a human-readable summary of a completed (or dry-run) batch."""
    lines = [f"Unit Assessment Batch Report — {case_id}", "=" * 60, ""]
    for i, r in enumerate(results, 1):
        start, end = r.page_range
        lines.append(
            f"{i:2d}. [{r.status.upper():7s}] pp.{start}–{end}  {r.label}"
            f"  (suffix: {r.output_suffix})"
        )
        if r.status == "dry_run":
            lines.append(f"    $ {r.command}")
        elif r.status == "pass":
            lines.append(
                f"    units={r.units_extracted}  findings={r.findings}"
                f"  siec={r.siec} no_siec={r.no_siec}"
                f" discussed={r.discussed} other={r.other_conclusion}"
                f"  passages={r.source_passages}  retries={r.retries}"
            )
            if r.boundary_warning:
                lines.append(
                    "    WARNING: multiple unit labels in this window"
                    " — check for boundary contamination"
                )
        elif r.status == "empty":
            lines.append(
                f"    No unit_assessments extracted"
                f" after {r.retries + 1} attempt(s)"
            )
        elif r.status == "failed":
            lines.append(f"    Error: {r.error}")
        elif r.status == "skipped":
            lines.append(f"    Skipped: {r.error or 'unknown reason'}")
        elif r.status == "skipped_existing":
            lines.append(f"    Draft already exists — skipped (units={r.units_extracted} findings={r.findings})")

    passed = sum(1 for r in results if r.status == "pass")
    empty = sum(1 for r in results if r.status == "empty")
    failed = sum(1 for r in results if r.status == "failed")
    skipped = sum(1 for r in results if r.status == "skipped")
    skipped_existing = sum(1 for r in results if r.status == "skipped_existing")
    dry = sum(1 for r in results if r.status == "dry_run")
    total_units = sum(r.units_extracted for r in results)
    total_findings = sum(r.findings for r in results)
    boundary_count = sum(1 for r in results if r.boundary_warning)
    retried = sum(1 for r in results if r.retries > 0)

    lines += ["", "=" * 60, f"Summary: {len(results)} window(s)"]
    status_line = f"  pass={passed}  empty={empty}  failed={failed}  skipped={skipped}  skipped_existing={skipped_existing}"
    if dry:
        status_line += f"  dry_run={dry}"
    lines.append(status_line)
    lines.append(f"  total unit_assessments={total_units}  total findings={total_findings}")
    if boundary_count:
        lines.append(f"  boundary warnings: {boundary_count} window(s) with multiple unit labels")
    if retried:
        lines.append(f"  retried: {retried} window(s) needed at least one retry")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generic unit assessment batch runner for Meridian"
    )
    parser.add_argument(
        "--case-id", required=True,
        help="Case ID (e.g. eu_sika_mbcc_2023)",
    )
    parser.add_argument(
        "--unit-type", default="",
        help="Unit type label for display only (e.g. crop, route, indication, country)",
    )
    parser.add_argument(
        "--start-page", type=int, default=None,
        help="First page to include in the planning scope",
    )
    parser.add_argument(
        "--end-page", type=int, default=None,
        help="Last page to include in the planning scope",
    )
    parser.add_argument(
        "--max-units", type=int, default=None,
        help="Maximum number of windows to run (default: all)",
    )
    parser.add_argument(
        "--window-size", type=int, default=20,
        help="Target pages per window passed to the planner (default: 20)",
    )
    parser.add_argument(
        "--max-cost", type=float, default=2.00,
        help="Maximum API cost per window in USD (default: 2.00)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print planned commands without calling Claude",
    )
    parser.add_argument(
        "--retry-empty", default=True, action="store_true",
        help="Retry once when a window returns no unit_assessments (default: on)",
    )
    parser.add_argument(
        "--no-retry-empty", dest="retry_empty", action="store_false",
        help="Disable retry-on-empty",
    )
    parser.add_argument(
        "--skip-existing", action="store_true",
        help=(
            "Skip windows whose output draft already exists. "
            "Safe to use when resuming an interrupted batch."
        ),
    )
    parser.add_argument(
        "--cache-dir", default=str(DEFAULT_CACHE_DIR),
        help=f"PDF text cache directory (default: {DEFAULT_CACHE_DIR})",
    )
    args = parser.parse_args(argv)

    anthropic_client = None
    if not args.dry_run:
        try:
            import anthropic as _anthropic
            anthropic_client = _anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
        except (ImportError, KeyError) as exc:
            print(f"ERROR: Cannot initialise Anthropic client: {exc}", file=sys.stderr)
            return 1

    try:
        results = run_batch(
            case_id=args.case_id,
            start_page=args.start_page,
            end_page=args.end_page,
            max_units=args.max_units,
            window_size=args.window_size,
            max_cost=args.max_cost,
            retry_empty=args.retry_empty,
            dry_run=args.dry_run,
            skip_existing=args.skip_existing,
            anthropic_client=anthropic_client,
            cache_dir=Path(args.cache_dir),
        )
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print(format_batch_report(results, args.case_id))

    failed = sum(1 for r in results if r.status == "failed")
    return 1 if failed > 0 and not args.dry_run else 0


if __name__ == "__main__":
    sys.exit(main())
